apiVersion: v1
kind: Service
metadata:
  name: todo-web-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: todo-web-template
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

---

apiVersion: v1
kind: Service
metadata:
  name: todo-postgres-service
spec:
  selector:
    app: todo-postgres-template
  ports:
    - protocol: TCP
      port: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: todo-redis-service
spec:
  selector:
    app: todo-redis-template
  ports:
    - protocol: TCP
      port: 6379

---
